menu:
  Home:
    - /
    - icon-home
  About:
    - /about
    - icon-info-circle

social:
  twitter: 
    - https://twitter.com/thefleshmonk
    - icon-twitter
    - rgb(61,212,229)
    - rgba(61, 212, 229, .1)
  ko-fi:
    - https://ko-fi.com/fleshmonk
    - icon-coffee
    - rgb(0, 0, 0)
    - rgba(0, 0, 0, .5)
  youtube:
    - https://www.youtube.com/channel/UC0ReVA3NT2KoJgTuLEVIK7g
    - icon-youtube
    - rgb(231, 106, 141)
    - rgba(231, 106, 141, .15)
  shop:
    - https://fleshmonk.storenvy.com/
    - icon-tag-fill
    - rgb(0, 153, 76)
    - rgba(0, 153, 76, .15)
  mail:
    - mailto:thefleshmonk@gmail.com
    - icon-mail-fill
    - rgb(51, 51, 255)
    - rgba(51, 51, 255, .15)